apiVersion: v1                              # Specifies the API version for Service resources
kind: Service                              # Declares this manifest as a Service

metadata:
  name: insurance-backend-service          # The name of the Service resource

spec:
  selector:
    app: insurance-backend                  # Selects pods with the label 'app: insurance-backend' to be targeted by this Service

  type: NodePort                           # Exposes the Service on each Node’s IP at a static port (NodePort)

  ports:
    - protocol: TCP                        # Protocol used by this Service port (TCP)
      port: 8081                          # Port number the Service exposes internally within the cluster
      targetPort: 8081                    # Port on the pod/container to forward traffic to
      nodePort: 30084                     # External port on each Node to access the Service; accessible via NodeIP:30084
